packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - zod@4.5.4

onlyBuiltDependencies:
  - esbuild
  - sharp
  - supabase
  - workerd
